
name: Run Node Extractor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 午夜运行
  workflow_dispatch:  # 支持手动触发

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
    - name: 检出仓库代码
      uses: actions/checkout@v4

    - name: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml
      env:
        PYTHONUNBUFFERED: 1  # 确保实时日志输出

    - name: 运行节点提取脚本
      run: python test/script.py
      env:
        PYTHONUNBUFFERED: 1  # 确保实时日志输出

    - name: 上传结果
      if: success()  # 仅在脚本成功运行时上传
      uses: actions/upload-artifact@v4
      with:
        name: working-nodes
        path: working_nodes.json
        retention-days: 7  # 保留 7 天

    - name: 失败时通知
      if: failure()
      uses: actions/github-script@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          try {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '节点提取脚本失败',
              body: '节点提取脚本运行失败，请检查日志。'
            });
          } catch (error) {
            console.log('无法创建 issue，可能未启用 Issues 功能: ', error);
          }

    - name: 失败时存档日志
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs
        path: |
          *.log
          working_nodes.json
        retention-days: 3  # 保留 3 天
```
