name: Run Node Extractor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to latest version

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'  # Cache pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml

    - name: Run node extractor script
      run: python test/script.py
      env:
        PYTHONUNBUFFERED: 1  # Ensure real-time logging

    - name: Upload results
      if: success()  # Only upload if script runs successfully
      uses: actions/upload-artifact@v4
      with:
        name: working-nodes
        path: working_nodes.json
        retention-days: 7  # Keep artifacts for 7 days

    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number || 1,
            body: 'Node extractor script failed. Please check the logs.'
          })

    - name: Archive logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs
        path: |
          *.log
          working_nodes.json
        retention-days: 3
